trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerImageName: 'alexandercsq/devops-portfolio-site'

steps:
- script: docker --version
  displayName: 'Check Docker Version'

- script: |
    docker build -t $(dockerImageName):$(Build.BuildId) ./site
    docker login -u $(dockerHubUsername) -p $(dockerHubPassword)
    docker push $(dockerImageName):$(Build.BuildId)
  displayName: 'Build & Push Docker Image'
  env:
    dockerHubUsername: $(dockerHubUsername)
    dockerHubPassword: $(dockerHubPassword)

jobs:
- deployment: DeployToDev
  displayName: 'Deploy to Dev Environment'
  environment: 'Dev'
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo 'Deploying to Dev Environment...'
          displayName: 'Deployment Step'
