trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerImageName: 'alexandercsq/devops-portfolio-site'
  
  env:
    dockerHubUsername: $(dockerHubUsername)
    dockerHubPassword: $(dockerHubPassword)

jobs:
- deployment: DeployToDev
  displayName: 'Deploy to Dev Environment'
  environment: 'Dev'
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo 'Deploying to Dev Environment...'
          displayName: 'Deployment Step'
